### ISSUE TITLE
Error Unbound public symbol IrSimpleFunctionPublicSymbolImpl on iOS

### ISSUE THREAD

**Issue by cahyofendhi** [adrielcafe/voyager#152] opened 2023-05-24 23:17 UTC
Error when running on iOS, with message 
```
There are still 3 unbound symbols after generation of IR module <shared>:
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.icon.<get-icon>|-5764684600227404327[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.options.<get-options>|7766868889533212780[0]
Unbound public symbol IrSimpleFunctionPublicSymbolImpl: cafe.adriel.voyager.navigator.tab/Tab.title.<get-title>|371973571756195065[0]
```
but if `cafe.adriel.voyager:voyager-tab-navigator` removed from `gradle`, workiing fine, please investigate this issue, thanks

version `1.0.0-rc06`

**Comment by Syer10** [comment] 2023-05-24 23:44
Duplicate of https://github.com/adrielcafe/voyager/issues/145
It is a compose bug that has to be fixed by the Compose plugin

**Closed** 2023-08-28 18:31 UTC
