### ISSUE TITLE
navigate to screen from BottomSheet 

### ISSUE THREAD

**Issue by Sadulla-Dev** [adrielcafe/voyager#316] opened 2024-01-22 11:26 UTC
How can we navigate to a screen from a bottom sheet?
if i navigate to Screen from BottomSheet, screen will be another bottom sheet. How can i do the opposite?

**Comment by Syer10** [comment] 2024-01-22 14:27
Duplicate of #310.
Please do not open multiple issues for the same question.

**Comment by Sadulla-Dev** [comment] 2024-01-23 05:32
sorry bro what can i do

**Closed** 2024-02-14 06:29 UTC
