### ISSUE TITLE
Save restoration doesn't work when Android destroys activity and create it again.

### ISSUE THREAD

**Issue by Grouen** [adrielcafe/voyager#6] opened 2021-08-07 19:31 UTC
When Android destroys activity Voyager serialize screens and then restore them. But they now are different objects and Voyager uses them  as "key" for "navigator.stateHolder.SaveableStateProvider" I think that is why Voyager can't restore state after activity recreation. (Same for  tabNavigator.stateHolder.SaveableStateProvider(currentTab))

**Comment by adrielcafe** [comment] 2021-08-08 21:15
Fixed in [1.0.0-beta04](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta04). Updated the [docs](https://github.com/adrielcafe/voyager/releases/tag/1.0.0-beta04) with instructions.

Thanks again @Grouen !

**Closed by adrielcafe** 2021-08-08 21:15 UTC

**Comment by Grouen** [comment] 2021-08-09 12:24
Still doesn't work when use transitions.

**Comment by adrielcafe** [comment] 2021-08-09 23:27
I was unable to reproduce using transitions with "Don't Keep Activities" enabled. But I've done as you sugested, can you validade with 1.0.0-beta05?

About the key, for that to work the `key` function must be a property. Since `Screen` is an interface it can't set the value itself, so every screen would have to do something like `override val key = generatedUniqueKey()`. This can be avoided by change the `Screen` to an abstract class, but I don't wan't to do that. 

I'll keep looking for options, maybe KSP could help. Feel free to open a new issue about that. And if you have any suggestion will be very welcome :)

**Comment by Grouen** [comment] 2021-08-10 11:06
> I was unable to reproduce using transitions with "Don't Keep Activities" enabled. But I've done as you sugested, can you validade with 1.0.0-beta05?

Issue is fixed, thanks.
