### ISSUE TITLE
Crash when Screen or Tab has lambda parameter

### ISSUE THREAD

**Issue by egorikftp** [adrielcafe/voyager#59] opened 2022-04-29 09:13 UTC
Hello, I have faced with issue.
Steps to reproduce:
1. Pass lambda parameter in Screen or Tab
2. Minimize application (go to launch screen f.e)
3. Observe crash 🙁 

Version: 1.0.0-rc01
Sample reproducable project: https://github.com/egorikftp/VoyagerCrash

Crash log:
```java
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.egoriku.voyagercrash.HomeTab)
        at android.os.Parcel.writeSerializable(Parcel.java:2165)
        at android.os.Parcel.writeValue(Parcel.java:1931)
        at android.os.Parcel.writeList(Parcel.java:1140)
        at android.os.Parcel.writeValue(Parcel.java:1880)
        at android.os.Parcel.writeList(Parcel.java:1140)
        at android.os.Parcel.writeValue(Parcel.java:1880)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1304)
        at android.os.Parcel.writeBundle(Parcel.java:1092)
        at android.os.Parcel.writeValue(Parcel.java:1849)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
        at android.os.Bundle.writeToParcel(Bundle.java:1304)
        at android.os.Parcel.writeBundle(Parcel.java:1092)
        at android.os.Parcel.writeValue(Parcel.java:1849)
        at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
        at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.io.NotSerializableException: androidx.compose.material.DrawerState
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
        at android.os.Parcel.writeSerializable(Parcel.java:2160)
        at android.os.Parcel.writeValue(Parcel.java:1931) 
        at android.os.Parcel.writeList(Parcel.java:1140) 
        at android.os.Parcel.writeValue(Parcel.java:1880) 
        at android.os.Parcel.writeList(Parcel.java:1140) 
        at android.os.Parcel.writeValue(Parcel.java:1880) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620) 
        at android.os.Bundle.writeToParcel(Bundle.java:1304) 
        at android.os.Parcel.writeBundle(Parcel.java:1092) 
        at android.os.Parcel.writeValue(Parcel.java:1849) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620) 
        at android.os.Bundle.writeToParcel(Bundle.java:1304) 
        at android.os.Parcel.writeBundle(Parcel.java:1092) 
        at android.os.Parcel.writeValue(Parcel.java:1849) 
        at android.os.BaseBundle.dumpStats(BaseBundle.java:1690) 
        at android.os.BaseBundle.dumpStats(BaseBundle.java:1727) 
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7870) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by adrielcafe** [comment] 2022-04-29 23:08
Please take a look at the [state restoration docs](https://voyager.adriel.cafe/state-restoration), As @Syer10 said, all `Screen` params must be `Serializable`.

Closing the issue since it's an expected behavior.

**Closed by adrielcafe** 2022-04-29 23:08 UTC

**Comment by wiryadev** [comment] 2024-05-13 16:49
> Because `Screen` is `Serializable`, you need to add `@Transient` and set a default value to non-serializable variables.

is there any side effect on using `@Transient` that we should be aware of?

**Comment by Syer10** [comment] 2024-05-13 16:52
You should generally avoid it. `@Transient` will initialize values as null when the app is restarted. Try to find other ways to do what you want.
